/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Course extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5765279498413324273L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Course\",\"namespace\":\"com.kafka.avro.model\",\"fields\":[{\"name\":\"courseId\",\"type\":\"string\"},{\"name\":\"courseName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Course> ENCODER =
      new BinaryMessageEncoder<Course>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Course> DECODER =
      new BinaryMessageDecoder<Course>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Course> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Course> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Course> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Course>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Course to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Course from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Course instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Course fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence courseId;
  private java.lang.CharSequence courseName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Course() {}

  /**
   * All-args constructor.
   * @param courseId The new value for courseId
   * @param courseName The new value for courseName
   */
  public Course(java.lang.CharSequence courseId, java.lang.CharSequence courseName) {
    this.courseId = courseId;
    this.courseName = courseName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return courseId;
    case 1: return courseName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: courseId = (java.lang.CharSequence)value$; break;
    case 1: courseName = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'courseId' field.
   * @return The value of the 'courseId' field.
   */
  public java.lang.CharSequence getCourseId() {
    return courseId;
  }


  /**
   * Sets the value of the 'courseId' field.
   * @param value the value to set.
   */
  public void setCourseId(java.lang.CharSequence value) {
    this.courseId = value;
  }

  /**
   * Gets the value of the 'courseName' field.
   * @return The value of the 'courseName' field.
   */
  public java.lang.CharSequence getCourseName() {
    return courseName;
  }


  /**
   * Sets the value of the 'courseName' field.
   * @param value the value to set.
   */
  public void setCourseName(java.lang.CharSequence value) {
    this.courseName = value;
  }

  /**
   * Creates a new Course RecordBuilder.
   * @return A new Course RecordBuilder
   */
  public static com.kafka.avro.model.Course.Builder newBuilder() {
    return new com.kafka.avro.model.Course.Builder();
  }

  /**
   * Creates a new Course RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Course RecordBuilder
   */
  public static com.kafka.avro.model.Course.Builder newBuilder(com.kafka.avro.model.Course.Builder other) {
    if (other == null) {
      return new com.kafka.avro.model.Course.Builder();
    } else {
      return new com.kafka.avro.model.Course.Builder(other);
    }
  }

  /**
   * Creates a new Course RecordBuilder by copying an existing Course instance.
   * @param other The existing instance to copy.
   * @return A new Course RecordBuilder
   */
  public static com.kafka.avro.model.Course.Builder newBuilder(com.kafka.avro.model.Course other) {
    if (other == null) {
      return new com.kafka.avro.model.Course.Builder();
    } else {
      return new com.kafka.avro.model.Course.Builder(other);
    }
  }

  /**
   * RecordBuilder for Course instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Course>
    implements org.apache.avro.data.RecordBuilder<Course> {

    private java.lang.CharSequence courseId;
    private java.lang.CharSequence courseName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.avro.model.Course.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.courseId)) {
        this.courseId = data().deepCopy(fields()[0].schema(), other.courseId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.courseName)) {
        this.courseName = data().deepCopy(fields()[1].schema(), other.courseName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Course instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.avro.model.Course other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.courseId)) {
        this.courseId = data().deepCopy(fields()[0].schema(), other.courseId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.courseName)) {
        this.courseName = data().deepCopy(fields()[1].schema(), other.courseName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'courseId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCourseId() {
      return courseId;
    }


    /**
      * Sets the value of the 'courseId' field.
      * @param value The value of 'courseId'.
      * @return This builder.
      */
    public com.kafka.avro.model.Course.Builder setCourseId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.courseId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'courseId' field has been set.
      * @return True if the 'courseId' field has been set, false otherwise.
      */
    public boolean hasCourseId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'courseId' field.
      * @return This builder.
      */
    public com.kafka.avro.model.Course.Builder clearCourseId() {
      courseId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'courseName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCourseName() {
      return courseName;
    }


    /**
      * Sets the value of the 'courseName' field.
      * @param value The value of 'courseName'.
      * @return This builder.
      */
    public com.kafka.avro.model.Course.Builder setCourseName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.courseName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'courseName' field has been set.
      * @return True if the 'courseName' field has been set, false otherwise.
      */
    public boolean hasCourseName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'courseName' field.
      * @return This builder.
      */
    public com.kafka.avro.model.Course.Builder clearCourseName() {
      courseName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Course build() {
      try {
        Course record = new Course();
        record.courseId = fieldSetFlags()[0] ? this.courseId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.courseName = fieldSetFlags()[1] ? this.courseName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Course>
    WRITER$ = (org.apache.avro.io.DatumWriter<Course>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Course>
    READER$ = (org.apache.avro.io.DatumReader<Course>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.courseId);

    out.writeString(this.courseName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.courseId = in.readString(this.courseId instanceof Utf8 ? (Utf8)this.courseId : null);

      this.courseName = in.readString(this.courseName instanceof Utf8 ? (Utf8)this.courseName : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.courseId = in.readString(this.courseId instanceof Utf8 ? (Utf8)this.courseId : null);
          break;

        case 1:
          this.courseName = in.readString(this.courseName instanceof Utf8 ? (Utf8)this.courseName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










